#!/usr/bin/env bun
/**
 * Step 4: 图片生成完成验证
 *
 * 1. draft.md humanizer receipt 后保持 immutable
 * 2. draft SLOT、image-plan、prompt 和 image 的拓扑一致性验证
 * 3. 信息图资产验证
 *
 * 用法:
 *   bun run step4-images.mjs <date-slug>
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { markStepDone, markStepFailed } from "./state-lib.mjs";
import { postsRoot, repoRoot } from "./path-resolver.mjs";
import { normalizeSlotDesc } from "./validation-lib.mjs";
import { extractBody, parseFrontmatter, readFmValue } from "./frontmatter-lib.mjs";
import {
  activeImageBasenames,
  activePromptBasenames,
  collectActiveAssets,
  normalizePromptSource,
  readImagePlan,
  validateVisualCoverage,
  validateBaoyuDesign,
  validateVisualPlanTopology,
  visualPromptDescription,
} from "./visual-plan-lib.mjs";
import { assertCurrentDraftHumanized } from "./humanizer-lib.mjs";

const allowDefaultImagePlan = process.argv.includes("--allow-default-image-plan");
const slug = process.argv.slice(2).find((arg) => !arg.startsWith("--"));
if (!slug) { process.stderr.write("usage: step4-images.mjs <date-slug>\n"); process.exit(1); }

const base = resolve(postsRoot(), slug);
const imgsDir = resolve(base, "imgs");
const promptsDir = resolve(imgsDir, "prompts");
const draftPath = resolve(base, "draft.md");

// 0. Pre-validation: draft.md must exist
if (!existsSync(draftPath)) {
  markStepFailed(slug, 4, "draft.md missing");
  process.exit(2);
}

// Step 4 must operate on the exact draft accepted by the mandatory
// humanization layer. This catches edits made after Step 3.
try {
  assertCurrentDraftHumanized(slug, { draftPath });
} catch (error) {
  const msg = error.message;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

// The same pre-humanizer protocol also has a read-only check mode. Running it
// here catches a mislabeled image or nested cover introduced after receipt;
// it never repairs draft.md during Step 4.
const preNormalizeScript = resolve(repoRoot(), ".agents/skills/wechat-article-write/scripts/pre-humanizer-normalize.mjs");
const normalization = spawnSync("bun", ["run", preNormalizeScript, slug, "--check"], {
  cwd: repoRoot(),
  encoding: "utf8",
  stdio: ["ignore", "pipe", "pipe"],
});
if (normalization.status !== 0) {
  const details = normalization.stderr?.trim() || normalization.stdout?.trim() || `exit ${normalization.status}`;
  const msg = `deterministic normalization is not complete after humanizer receipt; ${details}`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

// 0b. Batch mode is not part of this pipeline. Images must be generated by the
//     main Agent one-by-one with explicit --image paths so ordering and locks stay predictable.
const batchFiles = [resolve(base, "batch.json"), resolve(imgsDir, "batch.json")].filter((p) => existsSync(p));
if (batchFiles.length > 0) {
  const msg = `batch.json is not allowed in Step 4. 本管线要求主 Agent 串行逐张生图；删除 ${batchFiles.join(", ")} 后按逐张命令重跑。`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

// From the humanizer receipt onward draft.md is immutable. All image MIME,
// nested-cover, and coverImage normalization must have happened beforehand.
const coverPng = resolve(base, "cover.png");
const coverJpg = resolve(base, "cover.jpg");
let coverExt = "png";
if (!existsSync(coverPng) && existsSync(coverJpg)) coverExt = "jpg";
else if (existsSync(coverJpg)) {
  // Both exist — prefer jpg for compatibility with JPEG-producing backends.
  coverExt = "jpg";
}

// Fail if no cover image exists at all
if (!existsSync(coverPng) && !existsSync(coverJpg)) {
  const msg = "cover image missing: expected post root cover.png/cover.jpg. Run pre-humanizer-normalize.mjs before humanizer-zh for any existing nested cover; the renderer must write the generated cover at the post root.";
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

const currentDraft = readFileSync(draftPath, "utf8");
if (readFmValue(currentDraft, "coverImage") !== `cover.${coverExt}`) {
  const msg = `draft.md coverImage is not normalized to cover.${coverExt}; run pre-humanizer-normalize.mjs, humanizer-zh, mark-humanized, and Step 3 again`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

// Read draft.md (already validated to exist)
const draft = readFileSync(draftPath, "utf8");
const body = extractBody(draft);
const fm = parseFrontmatter(draft);

// 3b. The visual plan is the authoritative topology for every image asset.
const imagePlanPath = resolve(base, "image-plan.json");
let imagePlan;
try {
  imagePlan = readImagePlan(imagePlanPath);
} catch (error) {
  const msg = error.message;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}
if (!imagePlan) {
  const msg = `image-plan.json missing: ${imagePlanPath}. Write the visual plan before running Step 4.`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}
const topology = validateVisualPlanTopology(imagePlan, body);
if (!topology.ok) {
  const msg = `visual plan topology invalid: ${topology.errors.join("; ")}`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}
if (!allowDefaultImagePlan) {
  const coverageErrors = validateVisualCoverage(imagePlan, body).errors;
  if (coverageErrors.length > 0) {
    const msg = `visual coverage review invalid: ${coverageErrors.join("; ")}`;
    process.stderr.write(`step4: FAIL - ${msg}\n`);
    markStepFailed(slug, 4, msg);
    process.exit(2);
  }
}
if (!allowDefaultImagePlan) {
  const designErrors = validateBaoyuDesign(imagePlan);
  if (designErrors.length > 0) {
    const msg = `Baoyu visual design contract invalid: ${designErrors.join("; ")}`;
    process.stderr.write(`step4: FAIL - ${msg}\n`);
    markStepFailed(slug, 4, msg);
    process.exit(2);
  }
}

// 4. SLOT-only enforcement: no local imgs/ Markdown references allowed
const localImgRefs = [...draft.matchAll(/!\[[^\]]*\]\([^)]*imgs\//g)];
if (localImgRefs.length > 0) {
  markStepFailed(slug, 4, "draft.md contains local imgs/ image references — use SLOT_IMG_NN placeholders only");
  process.exit(2);
}

// 5. Plan/prompt/image consistency.  The body illustration list may be empty;
// the plan, not a quantity threshold, decides how many assets are required.
const imgs = existsSync(imgsDir)
  ? readdirSync(imgsDir).filter((f) => /\.(png|jpe?g|webp|gif)$/i.test(f))
  : [];
const activeAssets = collectActiveAssets(imagePlan, body, { blogSlug: fm?.blogSlug, slug });

function promptSource(node) {
  try {
    return normalizePromptSource(node?.prompt_source);
  } catch (error) {
    const msg = `invalid visual prompt source: ${error.message}`;
    process.stderr.write(`step4: FAIL - ${msg}\n`);
    markStepFailed(slug, 4, msg);
    process.exit(2);
  }
}

function requirePrompt(path, label, node) {
  const source = promptSource(node);
  if (!existsSync(path)) {
    const producerHint = source === "external"
      ? `producer=${node.producer}\nRun/delegate the selected producer first, save its final rendering prompt to the expected path, then rerun generate-image-prompts.mjs.`
      : "Run generate-image-prompts.mjs to materialize the adapter prompt, then rerun Step 4.";
    const msg = `${source} visual prompt missing for ${label}\nproducer=${node?.producer ?? "(adapter)"}\nexpected: ${path}\n${producerHint}`;
    process.stderr.write(`step4: FAIL - ${msg}\n`);
    markStepFailed(slug, 4, msg);
    process.exit(2);
  }
  if (readFileSync(path, "utf8").trim().length === 0) {
    const msg = `visual prompt is empty for ${label}: ${path}`;
    process.stderr.write(`step4: FAIL - ${msg}\n`);
    markStepFailed(slug, 4, msg);
    process.exit(2);
  }
}

function imageWithStem(stem) {
  return imgs.find((file) => file.replace(/\.(png|jpe?g|webp|gif)$/i, "") === stem) ?? null;
}

const coverPromptName = `00-cover-${normalizeSlotDesc(fm?.blogSlug ?? slug) || "article"}.md`;
requirePrompt(resolve(promptsDir, coverPromptName), "cover", imagePlan.cover);
requirePrompt(resolve(promptsDir, "00-infographic-core-summary.md"), "SLOT_IMG_00", imagePlan.infographic);

const missingAssets = [];
if (!imageWithStem("00-infographic-core-summary")) missingAssets.push("SLOT_IMG_00");
for (const slot of topology.bodySlots) {
  const entry = topology.entriesBySlot.get(slot.slot);
  const desc = visualPromptDescription(entry, slot);
  const nn = String(slot.slot).padStart(2, "0");
  const stem = `${nn}-${desc}`;
  requirePrompt(resolve(promptsDir, `${stem}.md`), `SLOT_IMG_${nn}`, entry);
  if (!imageWithStem(stem)) missingAssets.push(`SLOT_IMG_${nn} (expected imgs/${stem}.png)`);
}
if (missingAssets.length > 0) {
  const unprefixed = imgs.filter((file) => !/^\d{2}-/.test(file));
  const hint = unprefixed.length > 0
    ? `imgs/ 下有 ${unprefixed.length} 张图片未遵循 NN-<desc> 命名约定（如 ${unprefixed.slice(0, 3).join(", ")}），图片可能已生成但命名断裂。用多模态识别后运行 align-image-names.mjs 归位，不要重新生图。`
    : "请按 image-plan 的确定性 basename 生成缺失图片，不要使用随机文件名。";
  const msg = `Missing images for planned assets: ${missingAssets.join(", ")}. ${hint}`;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

// Only active assets are gates. Files left by an earlier plan remain visible
// as warnings and are never deleted automatically.
const activeImageNames = activeImageBasenames(activeAssets);
const staleImages = imgs.filter((file) => {
  const stem = file.replace(/\.(png|jpe?g|webp|gif)$/i, "");
  return !activeImageNames.has(stem);
});
if (staleImages.length > 0) {
  process.stderr.write(`step4: WARNING stale/unplanned images in imgs/: ${staleImages.join(", ")}\n`);
}

// 6. Infographic validation
const infoFiles = imgs.filter((f) => f.replace(/\.(png|jpe?g|webp|gif)$/i, "") === "00-infographic-core-summary");
if (infoFiles.length > 0) {
  const hasInfoRef = /infographic|SLOT_IMG_00/i.test(body);
  if (!hasInfoRef) {
    process.stderr.write("step4: WARNING infographic file exists but not referenced in draft.md\n");
  }
}

// 6b. Prompt/image basename contract for active assets. Stale prompts are
//     reported but do not become a gate for the current plan.
if (existsSync(promptsDir)) {
  const activePromptNames = activePromptBasenames(activeAssets);
  const promptFiles = readdirSync(promptsDir).filter((file) => file.endsWith(".md"));
  const stalePrompts = promptFiles.filter((file) => !activePromptNames.has(file.replace(/\.md$/i, "")));
  if (stalePrompts.length > 0) {
    process.stderr.write(`step4: WARNING stale/unplanned prompts in imgs/prompts/: ${stalePrompts.join(", ")}\n`);
  }
}

// Keep the freeze an explicit final invariant as well as a preflight. If a
// future helper ever writes draft.md inside Step 4, fail before marking the
// step complete instead of silently invalidating the receipt for Step 5.
try {
  assertCurrentDraftHumanized(slug, { draftPath });
} catch (error) {
  const msg = error.message;
  process.stderr.write(`step4: FAIL - ${msg}\n`);
  markStepFailed(slug, 4, msg);
  process.exit(2);
}

markStepDone(slug, 4, {
  imgs_dir: existsSync(imgsDir) ? imgsDir : null,
  cover_ext: coverExt,
  info_files: infoFiles.length,
});
process.stdout.write(JSON.stringify({ slug, step: 4, cover_ext: coverExt, info_files: infoFiles.length }) + "\n");
